export default {
  login: 'Demandtech',
  id: 102271199,
  node_id: 'U_kgDOBhiI3w',
  avatar_url: 'https://avatars.githubusercontent.com/u/102271199?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Demandtech',
  html_url: 'https://github.com/Demandtech',
  followers_url: 'https://api.github.com/users/Demandtech/followers',
  following_url:
    'https://api.github.com/users/Demandtech/following{/other_user}',
  gists_url: 'https://api.github.com/users/Demandtech/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Demandtech/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Demandtech/subscriptions',
  organizations_url: 'https://api.github.com/users/Demandtech/orgs',
  repos_url: 'https://api.github.com/users/Demandtech/repos',
  events_url: 'https://api.github.com/users/Demandtech/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Demandtech/received_events',
  type: 'User',
  site_admin: false,
  name: 'Adekunle Rasheed',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: 'Demandtvs',
  public_repos: 62,
  public_gists: 0,
  followers: 5,
  following: 14,
  created_at: '2022-03-24T02:10:36Z',
  updated_at: '2023-01-17T14:14:59Z',
}
